apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
spec:
  containers:
  - image: jenkins/jenkins:lts-alpine
    name: jenkins
    resources: {}
    volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: jenkins-vol1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-vol1
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5G
  hostPath:
    path: /jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-vol1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: local-path
